name: Sync to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git remote add hf-space https://Priyesh29:$HF_TOKEN@huggingface.co/spaces/Priyesh29/cognitive-retrieval-backend
          git push hf-space main --force
